export const APP_ROUTES = {
  dashboard: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  certificate: "/certificado/:code",
  accessDenied: "/acesso-negado",
  myProducts: "/meus-produtos",
  lessons: "/aulas",
  moduleLessons: "/aulas/:moduleId",
  templates: "/templates",
  mentorship: "/mentoria",
  events: "/eventos",
  prompts: "/prompts",
  userGpts: "/meus-gpts",
  challenges: "/desafios",
  certificates: "/certificados",
  notebook: "/meu-caderno",
  myMentorship: "/minha-mentoria",
  adminModules: "/admin/modules",
  adminLessons: "/admin/lessons",
  adminTemplates: "/admin/templates",
  adminPrompts: "/admin/prompts",
  adminGpts: "/admin/gpts",
  adminMentees: "/admin/mentees",
  menteeEditor: "/admin/mentees/:menteeId",
  adminUsers: "/admin/users",
  adminChallenges: "/admin/challenges",
  adminBanners: "/admin/banners",
  adminAppearance: "/admin/appearance",
  notFound: "*",
} as const;

export type AppRouteId = keyof typeof APP_ROUTES;
export type AppRouteGuard = "public" | "protected" | "admin" | "mentor" | "mentee";

export const APP_ROUTE_MANIFEST = [
  { id: "login", path: APP_ROUTES.login, guard: "public" },
  { id: "register", path: APP_ROUTES.register, guard: "public" },
  { id: "forgotPassword", path: APP_ROUTES.forgotPassword, guard: "public" },
  { id: "certificate", path: APP_ROUTES.certificate, guard: "public" },
  { id: "accessDenied", path: APP_ROUTES.accessDenied, guard: "public" },
  { id: "myProducts", path: APP_ROUTES.myProducts, guard: "protected" },
  { id: "dashboard", path: APP_ROUTES.dashboard, guard: "protected" },
  { id: "lessons", path: APP_ROUTES.lessons, guard: "protected" },
  { id: "moduleLessons", path: APP_ROUTES.moduleLessons, guard: "protected" },
  { id: "templates", path: APP_ROUTES.templates, guard: "protected" },
  { id: "mentorship", path: APP_ROUTES.mentorship, guard: "protected" },
  { id: "events", path: APP_ROUTES.events, guard: "protected" },
  { id: "prompts", path: APP_ROUTES.prompts, guard: "protected" },
  { id: "userGpts", path: APP_ROUTES.userGpts, guard: "protected" },
  { id: "challenges", path: APP_ROUTES.challenges, guard: "admin" },
  { id: "certificates", path: APP_ROUTES.certificates, guard: "protected" },
  { id: "notebook", path: APP_ROUTES.notebook, guard: "protected" },
  { id: "myMentorship", path: APP_ROUTES.myMentorship, guard: "mentee" },
  { id: "adminModules", path: APP_ROUTES.adminModules, guard: "admin" },
  { id: "adminLessons", path: APP_ROUTES.adminLessons, guard: "admin" },
  { id: "adminTemplates", path: APP_ROUTES.adminTemplates, guard: "mentor" },
  { id: "adminPrompts", path: APP_ROUTES.adminPrompts, guard: "admin" },
  { id: "adminGpts", path: APP_ROUTES.adminGpts, guard: "admin" },
  { id: "adminMentees", path: APP_ROUTES.adminMentees, guard: "mentor" },
  { id: "menteeEditor", path: APP_ROUTES.menteeEditor, guard: "mentor" },
  { id: "adminUsers", path: APP_ROUTES.adminUsers, guard: "mentor" },
  { id: "adminChallenges", path: APP_ROUTES.adminChallenges, guard: "mentor" },
  { id: "adminBanners", path: APP_ROUTES.adminBanners, guard: "mentor" },
  { id: "adminAppearance", path: APP_ROUTES.adminAppearance, guard: "mentor" },
  { id: "notFound", path: APP_ROUTES.notFound, guard: "public" },
] as const satisfies readonly {
  id: AppRouteId;
  path: (typeof APP_ROUTES)[AppRouteId];
  guard: AppRouteGuard;
}[];
