import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";

export interface Certificate {
  id: string;
  user_id: string;
  module_id: string;
  certificate_code: string;
  user_name: string;
  module_title: string;
  module_duration: string | null;
  issued_at: string;
}

export function useCertificates() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  // Fetch user's certificates
  const { data: certificates, isLoading } = useQuery({
    queryKey: ["certificates", user?.id],
    queryFn: async () => {
      if (!user) return [];
      
      const { data, error } = await supabase
        .from("certificates")
        .select("*")
        .eq("user_id", user.id)
        .order("issued_at", { ascending: false });
      
      if (error) throw error;
      return data as Certificate[];
    },
    enabled: !!user,
  });

  // Issue certificate
  const issueCertificateMutation = useMutation({
    mutationFn: async ({
      moduleId,
      userName,
      moduleTitle,
      moduleDuration,
    }: {
      moduleId: string;
      userName: string;
      moduleTitle: string;
      moduleDuration?: string;
    }) => {
      if (!user) throw new Error("User not authenticated");

      // Check if certificate already exists
      const { data: existing } = await supabase
        .from("certificates")
        .select("id")
        .eq("user_id", user.id)
        .eq("module_id", moduleId)
        .maybeSingle();

      if (existing) {
        return { alreadyExists: true };
      }

      const { data, error } = await supabase
        .from("certificates")
        .insert({
          user_id: user.id,
          module_id: moduleId,
          user_name: userName,
          module_title: moduleTitle,
          module_duration: moduleDuration,
          certificate_code: "", // Will be generated by trigger
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["certificates"] });
    },
  });

  // Verify certificate by code (public)
  const verifyCertificate = async (code: string) => {
    const { data, error } = await supabase
      .from("certificates")
      .select("*")
      .eq("certificate_code", code)
      .maybeSingle();
    
    if (error) throw error;
    return data as Certificate | null;
  };

  // Check if user has certificate for module
  const hasCertificate = (moduleId: string) => {
    return certificates?.some((c) => c.module_id === moduleId) || false;
  };

  return {
    certificates: certificates || [],
    isLoading,
    issueCertificate: issueCertificateMutation.mutate,
    isIssuing: issueCertificateMutation.isPending,
    verifyCertificate,
    hasCertificate,
  };
}
