import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { CircleHelp } from "lucide-react";
import { Modal } from "./ui/Modal";
import { Button } from "./ui/Button";
import { useStore } from "@/store/store";

const guides: Record<string, { title: string; steps: string[] }> = {
  inicio: { title: "Primeiros passos", steps: ["Em Configurações, confira nome, CRO, telefone e endereço do consultório.", "Em Pacientes, clique em Novo paciente e preencha os dados. Depois abra a ficha pelo nome.", "Registre o histórico de saúde em Anamnese. Use Tratamentos para montar o plano e seus valores.", "Em Financeiro, organize os vencimentos e registre o dinheiro que realmente recebeu.", "Confira o aviso de salvamento. Em demonstração, os dados são fictícios e não ficam guardados."] },
  pacientes: { title: "Pacientes e etapas", steps: ["Use a busca pelo nome, telefone ou CPF e clique no nome para abrir a ficha.", "Avaliação: consulta inicial. Aguardando decisão: existe uma proposta, mas o paciente ainda não confirmou se aceita.", "Em tratamento: há procedimentos aceitos para realizar. Em acompanhamento: procedimentos principais terminados, com revisões e pós-operatório. Alta: acompanhamento encerrado.", "Nem todo paciente precisa passar por Aguardando decisão. Consulta, retorno e pós-operatório podem seguir normalmente.", "A etapa apenas organiza a lista; não registra pagamento nem agenda retorno automaticamente."] },
  agenda: { title: "Agenda e consultas", steps: ["Clique em Nova consulta. Selecione o paciente, data, horário, procedimento e duração.", "Clique na consulta para editar ou remarcar. Também é possível arrastar, mas isso é opcional.", "Confirmar pelo WhatsApp abre uma mensagem para você revisar e enviar. O sistema não envia sozinho.", "Depois da resposta, marque Confirmado. Depois do atendimento, marque Atendido e registre a evolução.", "Para cobrar uma consulta, adicione-a ao plano em Tratamentos. Quando o paciente aceitar, o sistema abrirá a combinação de pagamento."] },
  anamnese: { title: "Histórico de saúde", steps: ["Converse com o paciente e registre as condições, alergias e medicamentos em uso.", "As alterações são salvas automaticamente. Confira o status de salvamento.", "Para coletar a assinatura, imprima a ficha e peça ao paciente ou responsável para assinar no papel.", "Depois, fotografe ou digitalize a ficha assinada e anexe em Imagens. Não há coleta de assinatura na tela."] },
  odontograma: { title: "Como marcar os dentes", steps: ["Confira se a dentição é permanente, de leite ou mista.", "Em Selecionar, clique em um dente para abrir os detalhes ou escolha vários para adicioná-los juntos ao plano.", "Para vários dentes, informe se o preço é por dente ou o total do conjunto. Confira o cálculo antes de adicionar.", "Escolha uma condição e clique no dente ou na face correspondente. Use Desfazer em caso de engano.", "O valor é definido para aquele paciente no momento de adicionar; a lista em Configurações serve apenas como atalho."] },
  tratamentos: { title: "Proposta e tratamento", steps: ["Adicione os procedimentos e valores que serão apresentados ao paciente.", "Ainda não aceito significa que é apenas uma proposta: ainda não é dívida nem valor a receber.", "Gerar PDF / imprimir é opcional. O sistema não envia sozinho; você escolhe como entregar.", "Quando o paciente aceitar, clique em Paciente aceitou — combinar pagamento.", "Procedimento realizado significa que o atendimento clínico foi feito. Isso nunca marca o valor como pago."] },
  evolucao: { title: "Registrar um atendimento", steps: ["Confira a data e escreva o que foi realizado no atendimento.", "Modelos rápidos servem como ponto de partida. Revise o texto para refletir o atendimento real.", "Clique em Registrar evolução (ou Salvar alterações, ao editar). Confira o registro e o status de salvamento."] },
  imagens: { title: "Fotos, exames e documentos", steps: ["Clique em Enviar e escolha uma foto, radiografia ou PDF. Classifique o arquivo para encontrá-lo depois.", "Abra a imagem para ampliar, girar ou ajustar a visualização. Esses controles ajudam a visualizar o arquivo.", "Para comparar, ative Comparar, selecione duas imagens e abra a comparação.", "Uma ficha assinada no papel pode ser fotografada ou digitalizada e anexada como documento."] },
  lembretes: { title: "Lembrar de entrar em contato", steps: ["Abra a ficha do paciente → Lembretes. Escreva o motivo do contato e escolha data e hora.", "Os atalhos preenchem o formulário. Confira a data combinada e clique em Criar lembrete para confirmar.", "Com três dias de antecedência, no dia e após o vencimento, o aviso de prazo fica vermelho. O aviso permanece até ser concluído.", "Clique em Entrar em contato para abrir o WhatsApp; revise a mensagem antes de enviar. Depois marque o lembrete como feito.", "Os avisos aparecem enquanto o sistema está aberto. Não são mensagens automáticas nem alertas garantidos com o site fechado."] },
  financeiro: { title: "Cobranças e dinheiro recebido", steps: ["Quando o paciente aceita um tratamento, informe à vista ou parcelado, a forma combinada e os vencimentos.", "Os vencimentos aparecem em Como ficou combinado. Criar uma parcela não significa que ela foi paga.", "Um dia antes, o sistema mostra Cobrar amanhã. No dia e depois do vencimento, o aviso fica vermelho.", "Quando o dinheiro entrar, clique em Registrar dinheiro recebido. Uma janela abre com valor, data e forma de pagamento para conferir.", "Se desejar, anexe uma foto ou PDF do comprovante. Ele fica ligado ao pagamento e também aparece em Imagens → Documento.", "Para pagamento parcial, informe só o valor recebido. O restante continua a receber. A realização clínica fica em Tratamentos."] },
  documentos: { title: "Documentos e assinaturas", steps: ["Confira nome, CRO e contatos em Configurações. Escolha o documento e revise o conteúdo antes de imprimir.", "Imprimir / PDF abre a janela do navegador: escolha a impressora ou Salvar como PDF. O envio por WhatsApp é feito por você.", "Anamnese: o paciente ou responsável assina no papel. Orçamento: há espaço para o aceite do paciente e assinatura do profissional.", "Receitas, atestados e recibos têm espaço para a assinatura do profissional. A foto cadastrada é apenas uma imagem; o sistema não oferece assinatura com certificado digital.", "Guarde a versão assinada e anexe uma cópia na ficha em Imagens. Gerar um PDF não guarda automaticamente uma cópia no prontuário.", "Modelos de receita devem ser revisados pelo dentista para cada caso. O sistema não valida doses, interações ou todas as alergias."] },
  configuracoes: { title: "Configurações e cópia de segurança", steps: ["Preencha o perfil do consultório. Esses dados aparecem nos documentos; o e-mail de contato não muda o e-mail de login.", "A assinatura digitalizada é uma foto enviada por você. Ela não é uma assinatura com certificado digital.", "Configure horários e preços. A definir significa que falta informar o valor; use zero somente para cortesia. Os valores podem ser ajustados em cada tratamento.", "Em Backup e dados, baixe uma cópia e guarde em local protegido. Restaurar uma cópia substitui os dados atuais.", "O PIN bloqueia a tela e é diferente da senha da conta. Para recuperar a senha, use Esqueci minha senha no login."] },
};

export function HelpCenter() {
  const [open, setOpen] = useState(false);
  const [topic, setTopic] = useState("inicio");
  const location = useLocation();
  const navigate = useNavigate();
  const settings = useStore(s => s.settings);
  const section = location.pathname.split("/")[1] || "inicio";
  const current = new URLSearchParams(location.search).get("aba") || section;
  return <>
    <Button variant="secondary" onClick={() => { setTopic(guides[current] ? current : "pacientes"); setOpen(true); }} icon={<CircleHelp className="h-4 w-4" />}>Ajuda</Button>
    <Modal open={open} onClose={() => setOpen(false)} title="Como usar o prontuário" subtitle="Escolha um assunto. Siga um passo de cada vez." size="lg">
      <label className="mb-5 block sm:hidden">Assunto<select className="input mt-2" value={topic} onChange={e => setTopic(e.target.value)}>{Object.entries(guides).map(([key, guide]) => <option key={key} value={key}>{guide.title}</option>)}</select></label>
      <div className="hidden sm:flex flex-wrap gap-2 mb-5">{Object.entries(guides).map(([key, guide]) => <button key={key} className={`rounded-xl border px-3 py-2 text-sm ${topic === key ? "bg-brand text-white border-brand" : "border-line text-ink"}`} onClick={() => setTopic(key)}>{guide.title}</button>)}</div>
      <h3 className="font-display text-2xl font-semibold mb-4">{guides[topic].title}</h3>
      <ol className="space-y-4">{guides[topic].steps.map((text, i) => <li key={text} className="flex gap-3 text-base leading-relaxed"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-brand-soft text-brand font-bold">{i + 1}</span><span>{text}</span></li>)}</ol>
      {topic === "inicio" && <div className="mt-6 rounded-xl border border-line p-4"><p className="font-semibold mb-2">Perfil do consultório</p>{[["Nome", settings.doctorName], ["CRO", settings.cro], ["Telefone", settings.phone], ["Endereço", settings.address]].map(([label, value]) => <p key={label} className="text-sm mb-1">{value ? "✓" : "○"} {label}: {value || "Falta preencher"}</p>)}<Button className="mt-3" onClick={() => { setOpen(false); navigate("/configuracoes?secao=perfil"); }}>Conferir meus dados</Button></div>}
    </Modal>
  </>;
}
